version: "3.3"

services: 
  app:
    container_name: restoneranfitrion_app_servicio_informacion_completa
    restart: always 
    build: .
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
    networks:
      - backend
    ports:
      - "5800:5000"
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    networks:
      - backend
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbbusiness_user
      MONGO_INITDB_ROOT_PASSWORD: mongodb1150
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9001:8081"
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongobusiness_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb4d2s
      ME_CONFIG_BASICAUTH_USERNAME: mongosicagguthfw2345f
      ME_CONFIG_BASICAUTH_PASSWORD: dasd23GGFa43dfe5fuj6c
      ME_CONFIG_MONGODB_URL: mongodb://mongodbbusiness_user:mongodb1150@mongo:27017/
  traefik: # apache.app.test - nginx.app.test
    image: traefik:v2.3.6
    labels: 
      - "traefik.http.routers.api.rule=Host(`localhost`)"
    ports: 
      - 100:80
      - 9004:8080
      - 443:443
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
      
networks:
  backend:
    driver: bridge
    ipam: 
      driver: default 








