version: "3.3"

services: 
  c-a-notificacion-tip:
    restart: always 
    build: .
    labels: 
      - "traefik.http.routers.c-a-notificacion-tip.rule=Host(`c-a-notificacion-tip.restoner-api.fun`)"
    networks:
      - backend
    links:
      - redis
      - postgres-master
  redis:
    container_name: redis_db
    restart: always
    image: "redis:6.0.16"
    networks:
      - backend
    volumes: 
      - cache:/data
    ports: 
      - "6000:6379"
  postgres-master:
    restart: always
    image: "bitnami/postgresql:13"
    networks:
      - backend
    ports:
      - "8620:5432"
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - DATABASE_HOST=127.0.0.1
      - POSTGRESQL_REPLICATION_USER=replicacion_usuasdaario_123f24
      - POSTGRESQL_REPLICATION_PASSWORD=replicacion_casdq41dontrasenia_123f24
      - POSTGRESQL_USERNAME=postgresxv7
      - POSTGRESQL_PASSWORD=4kdfghklfg1463hadgkj45345M
      - POSTGRESQL_DATABASE=postgresxv7
  postgresql-slave:
    image: 'bitnami/postgresql:13'
    ports:
      - "6432:5432"
    networks:
      - backend
    depends_on:
      - postgres-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicacion_usuasdaario_123f24
      - POSTGRESQL_REPLICATION_PASSWORD=replicacion_casdq41dontrasenia_123f24
      - POSTGRESQL_MASTER_HOST=postgres-master
      - POSTGRESQL_PASSWORD=4kdfghklfg1463hadgkj45345M
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
  traefik:
    image: traefik:v2.3.6
    ports: 
      - 5800:80
      - 443:443
    networks:
      - backend
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
      
networks:
  backend:
    driver: bridge
    ipam: 
      driver: default 
volumes:
  shared_database:







