version: "3.3"

services: 
  c-a-notificacion-tip:
    restart: always 
    build: .
    labels: 
      - "traefik.http.routers.c-a-notificacion-tip.rule=Host(`c-a-notificacion-tip.restoner-api.fun`)"
    networks:
      - backend
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes: 
      - shared_database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbbusiness_user
      MONGO_INITDB_ROOT_PASSWORD: mongodb1150
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9001:8081"
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongobusiness_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb4d2s
      ME_CONFIG_BASICAUTH_USERNAME: mongosicagguthfw2345f
      ME_CONFIG_BASICAUTH_PASSWORD: dasd23GGFa43dfe5fuj6c
      ME_CONFIG_MONGODB_URL: mongodb://mongodbbusiness_user:mongodb1150@mongo:27017/
  traefik:
    image: traefik:v2.3.6
    ports: 
      - 5800:80
      - 443:443
    networks:
      - backend
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
      
networks:
  backend:
    driver: bridge
    ipam: 
      driver: default 
volumes:
  shared_database:







